### ISSUE TITLE
Win drivers for 32 bit operating systems.

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/plutosdr-m2k-drivers-win#1]
Would it be possible for you to build the M2K Windows drivers for 32 bit versions of the operating system?
I have a Windows 8.1 Two-in-One with 64 bit quad core processor but has only 32 bit Windows installed.

Thanks

Doug

**Comment by mhennerich** [comment]
Fixed in this release:
https://github.com/analogdevicesinc/plutosdr-m2k-drivers-win/releases/tag/v0.5

Thanks for pointing out.

-Michael
