### ISSUE TITLE
Provide Link to the Releases section from README.md

### ISSUE THREAD

**Issue by r4d10n** [analogdevicesinc/plutosdr-m2k-drivers-win#2]
The windows driver files for PlutoSDR is available for download in the Releases section for the repository. 

https://github.com/analogdevicesinc/plutosdr-m2k-drivers-win/releases

**Comment by rgetz** [comment]
Done.

https://github.com/analogdevicesinc/plutosdr-m2k-drivers-win/blob/master/README.md

Thanks
-Robin
