### ISSUE TITLE
Can not set the PPM correction ?

### ISSUE THREAD

**Issue by zanco** [analogdevicesinc/plutosdr-m2k-drivers-win#3]
Hi, I can not find where to set the PPM correction for the Pluto SDR.

Any help with that? It's about 2 kHz off at 431 MHz

Thanks,

Ben

**Comment by rgetz** [comment]
do to it programatically, it should just be writing the correct iio attribute.

https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms2-ebz/hardware/tuning#oscillators

-Robin

**Comment by rgetz** [comment]
closing, based on no other follow up.
